###Raiz da aplicação
GET http://localhost:5240

### Listagem de Produtos
GET http://localhost:5240/produto/listar

###Busca de Produto por nome 
GET http://localhost:5240/produto/buscar/Celular

### Cadastro de Produtos
POST http://localhost:5240/produto/cadastrar/arroz/alimento/10

